### ISSUE TITLE
DatabaseRequestedEvent dont set `app` or `unit`

### ISSUE THREAD

**Issue by paulomach** [canonical/data-platform-libs#14]
### Bug Description

The emitter of `DatabaseRequestedEvent` don't set values to the `event.unit` nor `event.app` properties inherited from `RelationEvent`, so they are both defaulted to `None`.

For MySQL, the remote `unit.name` is used to index, within the database, the units specific user (e.g. `user`@`address`).

Also, without setting these properties, direct  access to relation remote app/unit databag is not possible, .e.g.:
```
(Pdb) event.relation.data[event.unit]
*** KeyError: None
```

### To Reproduce

1.Add a handler for `DatabaseRequestedEvent`
2.Inside the handler, try access `event.app` or `event.unit`

### Environment

Tested with v0.1 from charmhub

### Relevant log output

```shell
2022-07-04 21:14:26,327 ERROR    Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 281, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/main.py", line 431, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/main.py", line 142, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-81/charm/lib/charms/data_platform_libs/v0/database_provides.py", line 187, in _on_relation_changed
    self.on.database_requested.emit(event.relation)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/framework.py", line 316, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/framework.py", line 784, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/framework.py", line 857, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-81/charm/src/relations/provides.py", line 68, in _on_database_requested
    remote_host = event.relation.data[event.unit].get("private-address")
  File "/var/lib/juju/agents/unit-mysql-81/charm/venv/ops/model.py", line 890, in __getitem__
    return self._data[key]
KeyError: None
```

**Comment by marceloneppel** [comment]
Thanks for raising this issue, @paulomach! We should fix this as it is something expected on relation events.

In the meantime, can you check if something like the code below works?

```python
event.relation.data[event.relation.app]

# and also:

event.relation.data[event.relation.unit]
```

**Comment by paulomach** [comment]
Sure:

```
(Pdb) event.relation.data[event.relation.app]
{'data': '{}', 'database': 'application_first_database'}
(Pdb) event.relation.data[event.relation.unit]
*** AttributeError: 'Relation' object has no attribute 'unit'
(Pdb)
```

**Comment by marceloneppel** [comment]
There is a draft pull request about the fix for this in https://github.com/canonical/data-platform-libs/pull/15. It still needs some unit tests to be ready for review.

**Comment by marceloneppel** [comment]
Fix implemented on https://github.com/canonical/data-platform-libs/pull/15. Thanks for the help, @paulomach.

**Comment by marceloneppel** [comment]
New version of both libraries with the fixes are available on Charmhub.
