### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by beliaev-maksim** [canonical/data-platform-libs#58]
When try to import the library we get an exception:

```
2023-04-14 09:57:40 WARNING install Traceback (most recent call last):
2023-04-14 09:57:40 WARNING install   File "./src/charm.py", line 13, in <module>
2023-04-14 09:57:40 WARNING install     from charms.data_platform_libs.v0.data_interfaces import DatabaseRequires
2023-04-14 09:57:40 WARNING install   File "/var/lib/juju/agents/unit-mlflow-server-0/charm/lib/charms/data_platform_libs/v0/data_interfaces.py", line 356, in <module>
2023-04-14 09:57:40 WARNING install     class DataProvides(Object, ABC):
2023-04-14 09:57:40 WARNING install TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
2023-04-14 09:57:40 ERROR juju.worker.uniter.operation runhook.go:140 hook "install" (via hook dispatching script: dispatch) failed: exit status 1
```

one of the potential issues might be that our charm requires ops<2 which we set in [reqs.txt](https://github.com/canonical/mlflow-operator/blob/KF-1003-mysql-library/requirements.txt#L59) for our charm. While this lib requires ops>2. Not sure how charmcraft is going to resolve it.
but the issue might different, worth to investigate

**Comment by taurus-forever** [comment]
It sounds like a reason for reverting/refactoring https://github.com/canonical/data-platform-libs/pull/35 CC: @deusebio

**Comment by beliaev-maksim** [comment]
yes, I confirm that if we bump our charm to ops>2 then it works

maybe at least clear error if ops is of unsupported version?
since now it fails very cryptic

**Comment by deusebio** [comment]
Uhm, we specified this using charmlibs dependency (see [here](https://github.com/canonical/data-platform-libs/blob/main/lib/charms/data_platform_libs/v0/data_interfaces.py#L308)). It would actually be good if - when one does `charmcraft pack` - the consistency of these libraries are checked and errors are thrown otherwise

I can see that this can happen all the times that we have dependencies to comply with in our charmlibs unfortunately

**Comment by sergiusens** [comment]
using the new PYDEPS feature and having the libraries declare ops > 2 (for this case) would solve this issue.

**Comment by sergiusens** [comment]
recall that PYDEPS is currently on charmcraft edge only.

**Comment by beliaev-maksim** [comment]
@sergiusens that answers, then this ops dependency just got lost when we packed

@deusebio 
then I assume no action on the lib side

**Comment by deusebio** [comment]
:+1: Closing the issue then!
